name: TestDriver.ai Build
env:
  GO_VERSION: 1.25.6
  NODE_VERSION: 22
  GARALT_SECRET: ${{ secrets.GARALT }}
permissions:
  contents: read
  pull-requests: write
jobs:
  build_and_upload:
    name: Build for TestDriver.ai
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |-
        mkdir make
        echo "dummy" > make/dummy.exe
      shell: powershell
    - name: GARALT debug probe
      run: ls -R make/
      continue-on-error: true
    - name: Upload .exe artifact
      id: upload
      uses: actions/upload-artifact@v5
      with:
        name: windows-exe
        path: make/*.exe
on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  schedule:
  - cron: 0 21 * * *
  workflow_dispatch: null
